//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Reviews = new HashSet<Review>();
            this.WishLists = new HashSet<WishList>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

         [Required]
        public string Username { get; set; }

         [Required]
         [DataType(DataType.Password)]
        public string Password { get; set; }

         [Required]
         [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

         [Required]
        public string Country { get; set; }

         [Required]
        public string City { get; set; }

         [Required]
        public string Address { get; set; }

         [Required]
         [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }

         [Required]
        public int Phone { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
